# Generated by Django 5.2.7 on 2025-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="price_range",
            field=models.CharField(
                choices=[("€", "€"), ("€€", "€€"), ("€€€", "€€€")],
                default="€€",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="rating",
            field=models.FloatField(default=0, help_text="1-5 stars"),
        ),
        migrations.AddField(
            model_name="business",
            name="tags",
            field=models.CharField(
                blank=True, help_text="e.g., vegan,wifi,study-friendly", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(
                choices=[
                    ("cafe", "Cafe"),
                    ("bakery", "Bakery"),
                    ("tea_house", "Tea House"),
                    ("dessert", "Dessert Bar"),
                ],
                max_length=50,
            ),
        ),
    ]
