# Generated by Django 5.2.7 on 2025-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "businesses",
            "0002_business_price_range_business_rating_business_tags_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="category",
            field=models.CharField(
                choices=[
                    ("cafe", "Cafe"),
                    ("bakery", "Bakery"),
                    ("tea_house", "Tea House"),
                    ("dessert", "Dessert Bar"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="business",
            name="rating",
            field=models.FloatField(
                default=0, help_text="Average rating from 1.0 to 5.0"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated traits, e.g. vegan,wifi,study-friendly",
                max_length=200,
            ),
        ),
    ]
